# Generated by Django 4.1.3 on 2022-11-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vagas",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "Interesse"),
                    ("C", "Currículo enviado"),
                    ("E", "Entrevista"),
                    ("D", "Desafio técnico"),
                    ("R", "Aguardando retorno"),
                    ("F", "Finalizado"),
                    ("T", "Trabalhando"),
                ],
                max_length=30,
            ),
        ),
    ]
