# Generated by Django 4.1.3 on 2022-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_alter_vagas_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vagas",
            name="titulo",
            field=models.CharField(max_length=68),
        ),
    ]
